default: &default
  customer_api_endpoint: "http://localhost:8000/api/v1/"

development:
  <<: *default

test:
  <<: *default
  customer_api_endpoint: ""

production:
  <<: *default
  customer_api_endpoint: "b09ca30d-d179-4d77-fd31-0fbe9cd19e4f"
