default: &default
  customer_api_endpoint: "http://localhost:4000/api/v1/"

development:
  <<: *default

test:
  <<: *default
  customer_api_endpoint: ""

production:
  <<: *default
  customer_api_endpoint: "https://ruby-bank-customer-api.herokuapp.com/api/v1/"
